[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet LibraryManagement.API.dll"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
